language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

before_script:
    - composer install

script:
    - vendor/bin/phpunit --coverage-clover ./build/clover.xml

after_success:
    - php vendor/bin/php-coveralls -v
